= Getting Started
include::include.adoc[]

It's really easy to get started with *Spring Data JPA MongoDB Expressions*. This section shows you how.

== Installation

Add the following dependency in your Spring/Spring Boot project, where you already have
https://start.spring.io/#!dependencies=data-jpa[__spring-data-jpa__,role=external,window=_blank] dependency added.

=== Maven
[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>com.github.mhewedy</groupId>
  <artifactId>spring-data-jpa-mongodb-expressions</artifactId>
  <version>{revnumber}</version>
</dependency>
----

=== Gradle
[source,groovy,subs="attributes+"]
----
implementation 'com.github.mhewedy:spring-data-jpa-mongodb-expressions:{revnumber}'
----

IMPORTANT: *Spring Data JPA MongoDB Expressions* will not bring any dependencies with it - this is by design - so to avoid version overlap
in the dependencies. So make sure to setup your spring project to include the proper version of Spring Data JPA.

== Code changes
Three easy steps you need to do to be able to use __Spring Data JPA MongoDB Expressions__:

NOTE: All public APIs (classes and interfaces) of Spring Data JPA MongoDB Expressions are in the package `com.github.mhewedy.expressions.*`

1. You need to customize the base repository to be the `ExpressionsRepositoryImpl`:
+
[source,java]
----
@SpringBootApplication
@EnableJpaRepositories(repositoryBaseClass = ExpressionsRepositoryImpl.class)
public class MyApplication {

}
----
+
You can learn more about customizing the base repository in the
https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.customize-base-repository[spring data jpa documentations,role=external,window=_blank]
2. Change the parent repository of your JPA repositories to `ExpressionsRepository`
+
[source,java]
----
@Repository
public interface EmployeeRepository extends ExpressionsRepository<Employee, Long> {
}
----

3. Modify the search controller to accept `Expressions` in its parameter list:
+
[source,java]
----
@PostMapping("/search")
public ResponseEntity<Page<EmployeeDto>> search(@RequestBody Expressions expressions,
                                                Pageable pageable) {
    return ok().body(
                employeeRepository.findAll(expressions, pageable).map(employeeMapper::toDto)
        );
}
----

And that's it, you can now send Mongodb-like json queries to the API. (see <<query_specs.adoc#_query_specifications,Query Specifications>> )


